name: Build and replace JAR

on:
  push:
    branches: [ "main" ]
    paths:
      - "meta.data.action/src/main/**.java"
      - .github/workflows/build_jar.yml
      - meta.data.action/pom.xml
  pull_request:
    branches: [ "main" ]
    paths:
      - "meta.data.action/src/main/**.java"
      - .github/workflows/jar_build.yml
      - meta.data.action/pom.xml

jobs:
  Build-And-Replace-JAR:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build Package
      run: mvn -f ./meta.data.action/pom.xml install
    - name: Replace JAR
      run: |
            rm -f ./*.jar
            cp meta.data.action/target/*.jar ./
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto update JAR
